language: java

jdk:
  - openjdk8

addons:
  postgresql: "9.4"

before_script:
  - pip install --user codecov
  - bash -x prepare_travis.sh

env:
  - TEST_SUITE="travis_wait gradle check --stacktrace"   # unit tests
  - TEST_SUITE="gradle fullAcceptanceTest --stacktrace"  # acceptance tests

# run test suits in parallel
script: "$TEST_SUITE"

after_success:
  - codecov
  - jpadir/bin/codacy-coverage-reporter -l Java -r build/reports/jacoco/test/jacocoTestReport.xml
